title: tdy218's blog
description: My Personal Blog Site
author: Chris Tian
github: https://github.com/tdy218
about: I am middleware maintainer. Currently doing more about cloud computing in Nanjing, China and focused in JVM and Java EE.
disqus_shortname: tdy218-blog
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/tdy218"
    - icon: fa-github
      link: "https://github.com/tdy218"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://tdy218.blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
